pipeline {
    agent any 
    environment {
        APP_NAME = 'springboot'
        CONTAINER_PORT = '8000'
        HOST_PORT = '8000'
        GIT_CRED_ID = 'GITCRED'
        REPO_URL = 'https://github.com/rahulvadisetty91/devops-assesment.git'
        BUILD_NAME = "nginx" + ":$BUILD_NUMBER"
        ECR_REPO = "840955746374.dkr.ecr.us-east-1.amazonaws.com/web"
        ECR_REPO2 = "840955746374.dkr.ecr.us-east-1.amazonaws.com/web"+"nginx:$BUILD_NUMBER"
	SCRIPT = "nginx:$BUILD_NUMBER"
        AWS_DEFAULT_REGION = "us-east-1"
	NGINX = "nginx"
    }
       triggers {
 	    pollSCM('* * * * *')
 	}
    
    stages {
        
        
       
        
        stage('Image Build') {
            agent any
            steps {
                
                dir('./Lvl3/Option2/Docker-build/') {
                    sh "ls -la"
                     
                     sh "sudo docker build -t ${BUILD_NAME} ."
                }
                
               
               
            }
        }
        
        stage('Push Image') {
            agent any
            steps {
              
                withCredentials([string(credentialsId: 'ECR', variable: 'ECRPASS')]) {
                    
                   
                    sh 'echo ${ECRPASS} | sudo docker login --username AWS --password-stdin ${ECR_REPO}'
                }
                
                sh "sudo docker tag ${BUILD_NAME} ${ECR_REPO}:${NGINX}${BUILD_NUMBER}"
                sh "sudo docker push ${ECR_REPO}:${NGINX}${BUILD_NUMBER}"
                
            }
        }
        
        stage('Deploy App') {
            agent any
            steps {
               
               dir('/var/lib/jenkins/workspace/terraform-ecs/') {
                        
                        sh "sudo bash script.sh ${SCRIPT}"
                    
                } 
                
                dir('/var/lib/jenkins/workspace/terraform-ecs/') {
                        
                        
                        sh "ls -la"
                        sh "sudo /usr/local/bin/terraform init"
                        sh "sudo /usr/local/bin/terraform plan -out=tfplan -input=false"
                        sh "sudo /usr/local/bin/terraform apply -input=false tfplan"
                }
            }
        }
    }
}
